#!/bin/bash

[ -n "$VERBOSE" ] && echo "prerm called with argument \`$1'" >&2
[ -n "$VERBOSE" ] && set -x


#
# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
#
case "$1" in
    remove|deconfigure)

        # stop service if it is running.
        bash __INSTALL_3DIGIT__/bin/kafka-rest-stop
        if [ -d  __INSTALL_3DIGIT__/conf/ ]; then
           rm -Rf __INSTALL_3DIGIT__/conf/
        fi                
        rm -Rf __INSTALL_3DIGIT__/certs/
        rm -Rf __INSTALL_3DIGIT__/logs/
        rm -Rf  __INSTALL_3DIGIT__/config/saved/
        rm -Rf  __PREFIX__/kafka-rest/kafka-restversion
        if [ -f __PREFIX__/conf/conf.d/warden.kafka-rest.conf ]; then
            rm -Rf __PREFIX__/conf/conf.d/warden.kafka-rest.conf
        fi
        rm -Rf  __PREFIX__/conf/restart/kafka-rest-7.6.0.restart

    ;;
    upgrade)
        # stop service if it is running.
        bash __INSTALL_3DIGIT__/bin/kafka-rest-stop

        if [ -d __PREFIX__/kafka-rest/kafka-rest-5.1.2/conf ]; then
            rm -rf __PREFIX__/kafka-rest/kafka-rest-5.1.2/conf
        fi
    ;;  

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;  
esac    

